### ISSUE TITLE
Screenshot for your readme....

### ISSUE THREAD

**Issue by PySimpleGUI** [LP-Codes/Text-Case-Converter-Editor#1]
Hi!

Your readme.md file could really benefit from a screenshot like you posted over on the PySimpleGUI github.  In fact, you can use the SAME image.

![image](https://user-images.githubusercontent.com/66465441/119782575-fb6fd600-bee9-11eb-992a-cc24d12d0c16.png)

To add this image into your readme.md file, edit your readme.md file and add this line to it:

```
![image](https://user-images.githubusercontent.com/66465441/119782575-fb6fd600-bee9-11eb-992a-cc24d12d0c16.png)
```

Thanks for taking the time to post your wonderful creation!  Congrats on your project!  Keep building stuff!  The more you make the better you get!

**Comment by LP-Codes** [comment]
Thanks Have updated the readme ..
